### ISSUE TITLE
UNABLE to run the  jar

### ISSUE THREAD

**Issue by Nav15** [citiususc/BigBWA#5] opened 2016-06-02 11:27 UTC
Dear Jose,
I am using below command line to run the jar file:
"hadoop jar BigBWA.jar -archives bwa.zip -D mapreduce.input.fileinputformat.split.minsize=123641127 -D mapreduce.input.fileinputformat.split.maxsize=123641127  -algorithm mem -reads paired -index /Data/HumanBase/human_g1k_v37 -r ERR000030.fqBD ExitERR000030"
But getting below error:
16/05/31 17:15:54 INFO mapreduce.Job: Task Id : attempt_1464607670561_0009_m_000017_2, Status : FAILED
Error: java.lang.NullPointerException
    at java.io.Writer.<init>(Writer.java:88)
    at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:109)
    at BigBWA$BigBWAMap.setup(BigBWA.java:268)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:142)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:784)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

While debugging I found  statements : 
bw = new BufferedWriter(new OutputStreamWriter(fos));
bw2 = new BufferedWriter(new OutputStreamWriter(fos2));
 causing the issue,so I   for sake to run this I hardcoded the  path to create the  File 

tmpFileString = tmpDir+"/HadoopTMPFile-"+identificador+"-"+String.valueOf(jobID);
 replaced with 
tmpFileString = "/home/temp"
and similarly
tmpFileString2 = tmpDir+"/HadoopTMPFile-"+identificador+"_2"+"-"+String.valueOf(jobID);
relaced with
tmpFileString2 = /home/temp2
With this "bw" is working fine  but bw2 still giving NullPointerException.

As a workaround when I commented out to  check  some config issue at my end I  commented  the statement bw2 = new BufferedWriter(new OutputStreamWriter(fos2));
 In this case program worked fine  without any errors and part-0000 file also created  on hdfs. but no  output written in that file. Can you please advise here?

**Comment by jmabuin** [comment] 2016-06-02 13:44
Hi, thanks for your feedback.

The problem here is that in the code, the tmpDir relies in the Hadoop configuration variable hadoop.tmp.dir. if you don't have this variable set in your Hadoop configuration, then the tmpDir is null.

This is solved with commit  d9e03dc , that if this configuration valus is empty, it sets this variable as "/tmp/". Please, check if it works for you and let me know.

**Comment by Nav15** [comment] 2016-06-03 08:50
Hi, Thanks for your quick response.
I have  updated code to as per your suggestion but still I am getting the same NPE.

Getting   same  NullPointerException at line no 296.
                     //tmpDir = conf.get("hadoop.tmp.dir");
                        **tmpDir = conf.get("hadoop.tmp.dir","/tmp/");**
                        indexRoute = conf.get("indexRoute");
tmpFileString = tmpDir+"/HadoopTMPFile-"+identificador+"-"+String.valueOf(jobID);
 fout = new File(tmpFileString);
                        try {
                                fos = new FileOutputStream(fout);
                        } catch (FileNotFoundException e) {
                                // TODO Auto-generated catch block
                                e.printStackTrace();
                        }

```
                    **bw = new BufferedWriter(new OutputStreamWriter(fos));  //Line No 296**
```

Command Line to run this  is:
hadoop jar BigBWA.jar -archives bwa.zip -D mapreduce.input.fileinputformat.split.minsize=123641127 -D mapreduce.input.fileinputformat.split.maxsize=123641127 -mem -paired -index /Data/HumanBase/hg19 -r ERR000030.fqBD ERR000030

**Comment by jmabuin** [comment] 2016-06-03 09:02
I just added a new check for the tmpDir variable in cb44700

Does it works now?

Again thanks for your feedback.

**Comment by Nav15** [comment] 2016-06-03 09:22
No same issue at the place  : bw = new BufferedWriter(new OutputStreamWriter(fos));
Error: java.lang.NullPointerException
    at java.io.Writer.<init>(Writer.java:88)
    at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:109)
    at BigBWA$BigBWAMap.setup(BigBWA.java:273)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:142)

 /tmp is a local directory  in my master node. Hope this is OK.  

 Steps how I am running the jar:
$ cd BigBWA/build
From  inside  build directory I am running jar file, as jar file is present inside  the build directory:

**Comment by jmabuin** [comment] 2016-06-03 09:37
I am not able to reproduce this error.

Can you please do this?

1.- Add this at line 264: LOG.warn(tmpFileString); and check its value at the program output.
2.- Check if you are able to write in the /tmp/ dir in all your computing nodes.

**Comment by Nav15** [comment] 2016-06-03 09:50
Sorry but same error:
Can you check if  I am passring the  arguments correctly as shown below in program please?
1: Also   new  LOG.warn is not visible on the terminal, where should I check this log information?
2:  Yes it  is creating and writing some binat files under /tmp/hsperfdata_hadoop in master and namenodes;
-rw------- 1 hadoop hadoop 32768 Jun  3 15:15 22760
-rw------- 1 hadoop hadoop 32768 Jun  3 15:15 22255
-rw------- 1 hadoop hadoop 32768 Jun  3 15:15 22024
-rw------- 1 hadoop hadoop 32768 Jun  3 15:15 22423

 From where you are run jar file? Inside build 

Also what does it mean:

**bwa.zip - BWA library needed to execute together with Hadoop. It has to be uploaded to the Hadoop distributed cache.
 Can you explain how to put the generated .zip file in cache?**

16/06/03 15:10:18 INFO BigBWA: Arg: -algorithm
16/06/03 15:10:18 INFO BigBWA: Arg: mem
16/06/03 15:10:18 INFO BigBWA: Arg: -reads
16/06/03 15:10:18 INFO BigBWA: Arg: paired
16/06/03 15:10:18 INFO BigBWA: Arg: -index
16/06/03 15:10:18 INFO BigBWA: Arg: /Data/HumanBase/human_g1k_v37
16/06/03 15:10:18 INFO BigBWA: Arg: -r
16/06/03 15:10:18 INFO BigBWA: Arg: ERR000030.fqBD
16/06/03 15:10:18 INFO BigBWA: Arg: ExitERR000030
16/06/03 15:10:18 INFO BwaOptions: Received argument: -algorithm
16/06/03 15:10:18 INFO BwaOptions: Received argument: mem
16/06/03 15:10:18 INFO BwaOptions: Received argument: -reads
16/06/03 15:10:18 INFO BwaOptions: Received argument: paired
16/06/03 15:10:18 INFO BwaOptions: Received argument: -index
16/06/03 15:10:18 INFO BwaOptions: Received argument: /Data/HumanBase/human_g1k_v37
16/06/03 15:10:18 INFO BwaOptions: Received argument: -r
16/06/03 15:10:18 INFO BwaOptions: Received argument: ERR000030.fqBD
16/06/03 15:10:18 INFO BwaOptions: Received argument: ExitERR000030
16/06/03 15:10:19 INFO client.RMProxy: Connecting to ResourceManager at master/<XXX>
16/06/03 15:10:20 INFO input.FileInputFormat: Total input paths to process : 1
16/06/03 15:10:20 INFO mapreduce.JobSubmitter: number of splits:20
16/06/03 15:10:20 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1464868044355_0011
16/06/03 15:10:21 INFO impl.YarnClientImpl: Submitted application application_1464868044355_0011
16/06/03 15:10:21 INFO mapreduce.Job: The url to track the job: http://master:8088/proxy/application_1464868044355_0011/
16/06/03 15:10:21 INFO mapreduce.Job: Running job: job_1464868044355_0011
16/06/03 15:10:28 INFO mapreduce.Job: Job job_1464868044355_0011 running in uber mode : false
16/06/03 15:10:28 INFO mapreduce.Job:  map 0% reduce 0%
16/06/03 15:10:32 INFO mapreduce.Job: Task Id : attempt_1464868044355_0011_m_000004_0, Status : FAILED
Error: java.lang.NullPointerException
    at java.io.Writer.<init>(Writer.java:88)
    at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:109)
    at BigBWA$BigBWAMap.setup(BigBWA.java:274)
    at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:142)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:784)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)

**Comment by jmabuin** [comment] 2016-06-03 10:05
1.- You need to check the YARN logs, for example:

```
yarn logs -applicationId application_1462962580746_1680 | more
```

Where you should change the application id for yours, you can check it in the web interface.

2.- Sorry, but I am asking for to the /tmp directory itself, not /tmp/hsperfdata_hadoop. Please can you check it?

**Comment by Nav15** [comment] 2016-06-03 10:07
Inside /tmp there is no files generated. Only a directory named :hsperfdata_hadoop. All permissions are in place for writing  inside /tmp directory

**Comment by jmabuin** [comment] 2016-06-03 10:12
Great, what about the logs?

**Comment by Nav15** [comment] 2016-06-03 10:15
Logs:
2016-06-03 15:11:53,450 WARN [main] BigBWA: +tmpFileString:::::::::::::::file:/home/hadoop/hadoop_tempdir/HadoopTMPFile-11-11

[hadoop@master hadoop_tempdir]$ cd /home/hadoop/hadoop_tempdir/HadoopTMPFile-11-11
**-bash: cd: /home/hadoop/hadoop_tempdir/HadoopTMPFile-11-11: No such file or directory**

program not creating this directory ~/HadoopTMPFile-11-11

**Comment by jmabuin** [comment] 2016-06-03 10:24
I think this is a Hadoop configuration or a permissions issue. Can you please check if the route /home/hadoop/hadoop_tempdir/ actually exists and its permissions?

**Comment by Nav15** [comment] 2016-06-03 10:58
I have created a  single  user "hadoop" for my cluster:
 If  manually go an create a directory using mkdir  under:
/home/hadoop/hadoop_tempdir/
But through program  it   not creating the directory.
Any pointers please?

2016-06-03 16:17:40,934 WARN [main] BigBWA: +tmpFileString:::::::::::::::file:/home/hadoop/hadoop_tempdir/HadoopTMPFile-5-12
2016-06-03 16:17:40,934 WARN [main] BigBWA:  fout.canWrite():::::::::::::::false

**Comment by jmabuin** [comment] 2016-06-03 11:09
BigBWA writes this temp files where the configuration variable hadoop.tmp.dir points. It is supposed that you have write permissions and enough free space to write to this location.

By default, this location is /tmp/hadoop-${user.name} , so I suppose you changed it. My advise here is t left it unchanged.

Anyway, if you can not write to the hadoop.tmp.dir directory, this is not a BigBWA issue, so I am sorry, but I will close this issue in a few hours.

**Comment by Nav15** [comment] 2016-06-03 11:33
Jose, Can you  please advise as how  to perform the below step:
- **bwa.zip** - BWA library needed to execute together with Hadoop. It has to be uploaded to the Hadoop distributed cache.
  In README.md section this step has  mentioned.

**Comment by jmabuin** [comment] 2016-06-03 12:52
You do that with the option **-archives bwa.zip**

**Closed as completed by jmabuin** 2016-06-03 12:52 UTC
